version: "3"
services:
  consul:
    image: consul
    container_name: consul
    hostname: "consul"
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - main
  consul-agent:
    image: consul
    container_name: consul-agent
    command: agent -dev -retry-join consul
    depends_on:
      - consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - main
networks:
  main:
